In [ ]:
#Lab Assignment - 6
#DIGITAL IMAGE PROCESSING LAB
#Date – 05/11/2019
#Name – ASHISH GOYAL
#ID Number – 2016UCP1100

import cv2 as cv
import numpy as np
img = cv.imread('image.png',0)
cv.imshow('Input',img)
kernel = cv.getStructuringElement(cv.MORPH_ELLIPSE,(9,9))
print(kernel)
opening = cv.morphologyEx(img, cv.MORPH_OPEN, kernel)
#cv.imshow('Circles',opening)
new = img - opening
#cv.imshow('Lines',new)

kernel1 = np.ones((3,3),np.uint8)
kernel2 = np.ones((3,3),np.uint8)

erosion = cv.erode(new,kernel1,iterations = 1)
dilation = cv.dilate(erosion,kernel2,iterations = 1)
cv.imshow('Lines Final',dilation)
cv.imwrite('line.png',dilation)

kernel3 = cv.getStructuringElement(cv.MORPH_ELLIPSE,(5,5))

erosion1 = cv.erode(opening,kernel3,iterations = 1)
dilation1 = cv.dilate(erosion1,kernel3,iterations = 1)
cv.imshow('Circle Final',dilation1)
cv.imwrite('circle.png',dilation1)

k = cv.waitKey(0) & 0xFF    #for 64 bit machine
cv.destroyAllWindows()

[[0 0 0 0 1 0 0 0 0]
 [0 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 0]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [0 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 0]
 [0 0 0 0 1 0 0 0 0]]
