In [ ]:
# Lab Assignment - 2
# DIP Lab
# Date - 20 Aug 19
# Name - Ashish Goyal
# Id - 2016ucp1100
import cv2  
import numpy as np
#function cv2.imread() to read an image
img_object = cv2.imread('img2.jpg',0) #Loads a color image. Any transparency of image will be neglected. It is the default flag.
print(type(img_object))
#print(img_object1) #to show image in matrix form
height = img_object.shape[0]
width = img_object.shape[1]
cv2.imshow('Initial Image',img_object)
print(height,width)
print(img_object)
final_img= cv2.imread('img2.jpg',0)
final_img =final_img[1:height, 1:width]
for i in range(1,height-1):
    temp_list=[]
    for j in range (1,width-1):
        val=0
        if (img_object[i][j] >= img_object[i-1][j-1]):
            val = val + 1
        if (img_object[i][j] >= img_object[i-1][j]):
            val = val + 2
        if (img_object[i][j] >= img_object[i-1][j+1]):
            val = val + 4
        if (img_object[i][j] >= img_object[i][j+1]):
            val = val + 8
        if (img_object[i][j] >= img_object[i+1][j+1]):
            val = val + 16
        if (img_object[i][j] >= img_object[i+1][j]):
            val = val + 32
        if (img_object[i][j] >= img_object[i+1][j-1]):
            val = val + 64
        if (img_object[i][j] >= img_object[i][j-1]):
            val = val + 128
        final_img[i][j] = val
            

print (final_img)
cv2.imshow('Final Image',final_img)
cv2.imwrite('LBP_output.jpg',final_img)
k = cv2.waitKey(0) & 0xFF    #for 64 bit machine
cv2.destroyAllWindows()

<class 'numpy.ndarray'>
240 320
[[ 82  38  47 ...  80  76  75]
 [ 65  40  38 ... 154 151 151]
 [ 50  44  30 ... 199 199 199]
 ...
 [141 143 140 ...  98 109 126]
 [119 110  97 ...  92 107 110]
 [ 89  74  57 ... 119 127 104]]
[[ 40  38  30 ... 154 151 151]
 [ 44  26  61 ...  15  15  15]
 [ 54  78  12 ... 127 111 207]
 ...
 [143 135 255 ...  56 108  66]
 [110 255 121 ...  48 224 231]
 [ 74 120 120 ...   0 192 145]]
