In [ ]:
# Lab Assignment - 2
# DIP Lab
# Date - 20 Aug 19
# Name - Ashish Goyal
# Id - 2016ucp1100
import cv2  
import numpy as np
import math 
#function cv2.imread() to read an image
img_object = cv2.imread('image1.jpg',0) #Loads a color image. Any transparency of image will be neglected. It is the default flag.
print(type(img_object))
#print(img_object1) #to show image in matrix form
height = img_object.shape[0]
width = img_object.shape[1]
cv2.imshow('Initial Image',img_object)
print(height,width)
print(img_object)
vertical_img= cv2.imread('image1.jpg',0)
vertical_img =vertical_img[1:height, 1:width]

horizontal_img= cv2.imread('image1.jpg',0)
horizontal_img =horizontal_img[1:height, 1:width]

magnitude_img= cv2.imread('image1.jpg',0)
magnitude_img =magnitude_img[1:height, 1:width]

orientation_img= cv2.imread('image1.jpg',0)
orientation_img =orientation_img[1:height, 1:width]
c=0
for i in range(1,height-1):
    temp_list=[]
    for j in range (1,width-1):
        val=0
        val = val + img_object[i-1][j-1]*-1
        val = val + img_object[i-1][j]*0
        val = val + img_object[i-1][j+1]*1
        val = val + img_object[i][j+1]*2
        val = val + img_object[i+1][j+1]*1
        val = val + img_object[i+1][j]*0
        val = val + img_object[i+1][j-1]*-1
        val = val + img_object[i][j-1]*-2
        val = val + img_object[i][j]*0  #center pixel
        if (val<0):
            c=c+1
        vertical_img[i][j] = val
            

print (vertical_img)
cv2.imshow('Vertical Image',vertical_img)
cv2.imwrite('output_Vertical_Sobel.jpg',vertical_img)

for i in range(1,height-1):
    temp_list=[]
    for j in range (1,width-1):
        val=0
        val = val + img_object[i-1][j-1]*-1
        val = val + img_object[i-1][j]*-2
        val = val + img_object[i-1][j+1]*-1
        val = val + img_object[i][j+1]*0
        val = val + img_object[i+1][j+1]*1
        val = val + img_object[i+1][j]*2
        val = val + img_object[i+1][j-1]*1
        val = val + img_object[i][j-1]*0
        val = val + img_object[i][j]*0
        if (val<0):
            c=c+1
        horizontal_img[i][j] = val

cv2.imshow('Horizontal Image',horizontal_img)
cv2.imwrite('output_Horizontal_Sobel.jpg',horizontal_img)

#print (c)
magnitude_img = horizontal_img + vertical_img
cv2.imshow('Magnitude Image',magnitude_img)
cv2.imwrite('output_Magnitude_Sobel.jpg',magnitude_img)

for i in range(1,height-1):
    temp_list=[]
    for j in range (1,width-1):
        if horizontal_img[i][j]!=0:
            orientation_img[i][j] = int(math.degrees(math.atan(vertical_img[i][j]/horizontal_img[i][j])))
        else:
            orientation_img[i][j] = 90
    
cv2.imshow('orientation Image',orientation_img)
cv2.imwrite('output_orientation_img.jpg',orientation_img)



k = cv2.waitKey(0) & 0xFF    #for 64 bit machine
cv2.destroyAllWindows()

<class 'numpy.ndarray'>
1131 1698
[[ 76  76  75 ...  72  72  71]
 [ 76  76  76 ...  71  71  71]
 [ 75  75  76 ...  71  70  71]
 ...
 [ 85  89  84 ... 106 108 112]
 [ 94  83  84 ... 104 103 109]
 [ 86  88  84 ... 105 106 113]]
[[ 76  76  76 ...  71  71  71]
 [ 75   0   0 ... 253 255 255]
 [ 76   1   2 ... 254 252   0]
 ...
 [ 89  10   7 ... 238 249  31]
 [ 83 252 252 ... 240 253  25]
 [ 88 233 244 ... 241 250  24]]
